services:
    # this is a GUI for accessing the local database
    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080

    # here is where wordpress lives
    wordpress:
        image: wordpress:latest
        restart: always
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
            WORDPRESS_DB_NAME: ${DB_NAME}
        volumes:
            - wp_data:/var/www/html

    # a mysql instance
    db:
        image: mysql:latest
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        expose:
            - 3306
            - 33060
        volumes:
            - db_data:/var/lib/mysql

volumes:
    wp_data:
    db_data: